project_id = "zznsqmcewtzlnfoiefkk"

[auth]
site_url = "https://climbing-tracker-tan.vercel.app"
additional_redirect_urls = [
  "https://climbing-tracker-tan.vercel.app",
  "http://localhost:5173",
  "http://localhost:4173",
]
[storage.vector]
enabled = false
