import XCTest
import SendLogWatchCore

/// Regression coverage for issue #189: the watch and web computed ACWR with
/// different algorithms (a 28-day series seeded at the raw first-day value,
/// vs. the web's 90-day series seeded at the window mean), so the two
/// surfaces disagreed even for the exact same underlying session data (the
/// original report: watch showed 1.54, phone showed 1.37 for the same
/// account at the same time). `ewmaAcwr`/`dailyLoadSeries` in ACWR.swift now
/// mirror `ewmaAcwr` in src/lib/metrics.ts exactly — see that file's
/// KEEP-IN-SYNC comment.
final class ACWRTests: XCTestCase {
    func testFlatLoadRatioIsOne() {
        // Acute and chronic EWMAs both converge to the same constant, so the
        // ratio is exactly 1 regardless of span.
        let flat = Array(repeating: 10.0, count: 90)
        XCTAssertEqual(ewmaAcwr(dailyLoads: flat) ?? -1, 1.0, accuracy: 1e-9)
    }

    func testEmptyLoadIsNil() {
        XCTAssertNil(ewmaAcwr(dailyLoads: []))
    }

    func testAllZeroLoadIsNil() {
        XCTAssertNil(ewmaAcwr(dailyLoads: Array(repeating: 0.0, count: 90)))
    }

    /// Watch/web parity lock (issue #189): the exact same 90-day series must
    /// produce the exact same ratio on both sides. The fixture (generated by
    /// integer arithmetic only — no transcendental functions — so it's
    /// reproducible bit-for-bit across Swift and JS) and the expected ratio
    /// are pinned identically in src/lib/metrics.test.ts's "watch/web ACWR
    /// parity" test; a future change to either implementation's math that
    /// silently re-diverges from the other fails loudly here instead of
    /// quietly drifting again.
    func testMatchesWebFixtureVector() {
        let dailyLoads = (0..<90).map { Double(($0 * 13 + 7) % 47) }
        XCTAssertEqual(ewmaAcwr(dailyLoads: dailyLoads) ?? -1, 1.1151915681290694, accuracy: 1e-9)
    }

    // MARK: dailyLoadSeries

    private func date(year: Int, month: Int, day: Int) -> Date {
        var comps = DateComponents()
        comps.year = year
        comps.month = month
        comps.day = day
        comps.hour = 12 // noon: clear of any DST-transition edge cases
        return Calendar.gregorianLocal.date(from: comps)!
    }

    func testDailyLoadSeriesIsOldestToNewestWithZeroForMissingDays() {
        let now = date(year: 2026, month: 7, day: 12)
        let rows = [
            SessionLoadRow(date: "2026-07-12", load: 30), // today (last element)
            SessionLoadRow(date: "2026-07-10", load: 20), // 2 days ago
            SessionLoadRow(date: "2026-06-01", load: 999), // outside a 3-day window, ignored
        ]
        let series = dailyLoadSeries(rows: rows, days: 3, now: now)
        // Oldest → newest: 2026-07-10, 2026-07-11, 2026-07-12.
        XCTAssertEqual(series, [20, 0, 30])
    }

    func testDailyLoadSeriesSumsMultipleSessionsOnTheSameDay() {
        let now = date(year: 2026, month: 7, day: 12)
        let rows = [
            SessionLoadRow(date: "2026-07-12", load: 10),
            SessionLoadRow(date: "2026-07-12", load: 15),
        ]
        let series = dailyLoadSeries(rows: rows, days: 1, now: now)
        XCTAssertEqual(series, [25])
    }

    func testDailyLoadSeriesTreatsNilLoadAsZero() {
        let now = date(year: 2026, month: 7, day: 12)
        let rows = [SessionLoadRow(date: "2026-07-12", load: nil)]
        let series = dailyLoadSeries(rows: rows, days: 1, now: now)
        XCTAssertEqual(series, [0])
    }
}
