import XCTest
import SendLogWatchCore

/// Regression coverage for issue #189: the watch and web computed ACWR with
/// different algorithms (a 28-day series seeded at the raw first-day value,
/// vs. the web's 90-day series seeded at the window mean), so the two
/// surfaces disagreed even for the exact same underlying session data (the
/// original report: watch showed 1.54, phone showed 1.37 for the same
/// account at the same time). `ewmaAcwr`/`dailyLoadSeries` in ACWR.swift now
/// mirror `ewmaAcwr` in src/lib/metrics.ts exactly — see that file's
/// KEEP-IN-SYNC comment.
final class ACWRTests: XCTestCase {
    func testFlatLoadRatioIsOne() {
        // Acute and chronic EWMAs both converge to the same constant, so the
        // ratio is exactly 1 regardless of span.
        let flat = Array(repeating: 10.0, count: 90)
        XCTAssertEqual(ewmaAcwr(dailyLoads: flat) ?? -1, 1.0, accuracy: 1e-9)
    }

    func testEmptyLoadIsNil() {
        XCTAssertNil(ewmaAcwr(dailyLoads: []))
    }

    func testAllZeroLoadIsNil() {
        XCTAssertNil(ewmaAcwr(dailyLoads: Array(repeating: 0.0, count: 90)))
    }

    /// Watch/web parity lock (issue #189): the exact same 90-day series must
    /// produce the exact same ratio on both sides. The fixture (generated by
    /// integer arithmetic only — no transcendental functions — so it's
    /// reproducible bit-for-bit across Swift and JS) and the expected ratio
    /// are pinned identically in src/lib/metrics.test.ts's "watch/web ACWR
    /// parity" test; a future change to either implementation's math that
    /// silently re-diverges from the other fails loudly here instead of
    /// quietly drifting again.
    func testMatchesWebFixtureVector() {
        let dailyLoads = (0..<90).map { Double(($0 * 13 + 7) % 47) }
        XCTAssertEqual(ewmaAcwr(dailyLoads: dailyLoads) ?? -1, 1.1151915681290694, accuracy: 1e-9)
    }

    // MARK: dailyLoadSeries

    private func date(year: Int, month: Int, day: Int) -> Date {
        var comps = DateComponents()
        comps.year = year
        comps.month = month
        comps.day = day
        comps.hour = 12 // noon: clear of any DST-transition edge cases
        return Calendar.gregorianLocal.date(from: comps)!
    }

    func testDailyLoadSeriesIsOldestToNewestWithZeroForMissingDays() {
        let now = date(year: 2026, month: 7, day: 12)
        let rows = [
            SessionLoadRow(date: "2026-07-12", load: 30), // today (last element)
            SessionLoadRow(date: "2026-07-10", load: 20), // 2 days ago
            SessionLoadRow(date: "2026-06-01", load: 999), // outside a 3-day window, ignored
        ]
        let series = dailyLoadSeries(rows: rows, days: 3, now: now)
        // Oldest → newest: 2026-07-10, 2026-07-11, 2026-07-12.
        XCTAssertEqual(series, [20, 0, 30])
    }

    func testDailyLoadSeriesSumsMultipleSessionsOnTheSameDay() {
        let now = date(year: 2026, month: 7, day: 12)
        let rows = [
            SessionLoadRow(date: "2026-07-12", load: 10),
            SessionLoadRow(date: "2026-07-12", load: 15),
        ]
        let series = dailyLoadSeries(rows: rows, days: 1, now: now)
        XCTAssertEqual(series, [25])
    }

    func testDailyLoadSeriesTreatsNilLoadAsZero() {
        let now = date(year: 2026, month: 7, day: 12)
        let rows = [SessionLoadRow(date: "2026-07-12", load: nil)]
        let series = dailyLoadSeries(rows: rows, days: 1, now: now)
        XCTAssertEqual(series, [0])
    }
}

final class StatusPresentationTests: XCTestCase {
    func testACWRRiskBandsMatchWebBoundaries() {
        XCTAssertEqual(StatusPresentation.acwrRiskBand(0.799), .low)
        XCTAssertEqual(StatusPresentation.acwrRiskBand(0.8), .low)
        XCTAssertEqual(StatusPresentation.acwrRiskBand(0.801), .optimal)
        XCTAssertEqual(StatusPresentation.acwrRiskBand(1.3), .optimal)
        XCTAssertEqual(StatusPresentation.acwrRiskBand(1.301), .caution)
        XCTAssertEqual(StatusPresentation.acwrRiskBand(1.5), .caution)
        XCTAssertEqual(StatusPresentation.acwrRiskBand(1.501), .high)
    }

    func testACWRTrackClampsToZeroThroughTwoScale() {
        XCTAssertEqual(StatusPresentation.acwrTrackPosition(-1), 0)
        XCTAssertEqual(StatusPresentation.acwrTrackPosition(0.8), 0.4)
        XCTAssertEqual(StatusPresentation.acwrTrackPosition(1.3), 0.65)
        XCTAssertEqual(StatusPresentation.acwrTrackPosition(1.5), 0.75)
        XCTAssertEqual(StatusPresentation.acwrTrackPosition(3), 1)
    }

    func testNilAndNonFiniteValuesStayUnknown() {
        XCTAssertNil(StatusPresentation.acwrRiskBand(nil))
        XCTAssertNil(StatusPresentation.acwrRiskBand(.nan))
        XCTAssertNil(StatusPresentation.acwrRiskBand(.infinity))
        XCTAssertNil(StatusPresentation.acwrTrackPosition(nil))
        XCTAssertNil(StatusPresentation.acwrTrackPosition(.nan))
    }

    func testReadinessProgressClampsAndNilDoesNotBecomeZero() {
        XCTAssertNil(StatusPresentation.readinessProgress(nil))
        XCTAssertEqual(StatusPresentation.readinessProgress(-10), 0)
        XCTAssertEqual(StatusPresentation.readinessProgress(82), 0.82)
        XCTAssertEqual(StatusPresentation.readinessProgress(120), 1)
    }

    func testReadinessZoneLabelsAreNormalizedWithoutInventingUnknownZones() {
        XCTAssertEqual(StatusPresentation.readinessZoneLabel("recover"), "Recover")
        XCTAssertEqual(StatusPresentation.readinessZoneLabel("Maintain"), "Maintain")
        XCTAssertEqual(StatusPresentation.readinessZoneLabel("PUSH"), "Push")
        XCTAssertNil(StatusPresentation.readinessZoneLabel(nil))
        XCTAssertNil(StatusPresentation.readinessZoneLabel("unknown"))
    }
}

/// Cross-pinning fixture for the readiness/ACWR math shared with the web
/// (src/lib/metrics.ts), the health core (native-plugins/sendlog-health-core)
/// and the native app (native/SendmeterNative). Same bytes as
/// src/lib/readinessAcwrParity.test.ts and the other two Swift suites; a
/// drift in any implementation's numbers fails the suite that owns it.
///
/// The watch's `ACWRRiskBand` is a deliberately compact 4-band presentation
/// (no separate sub-0.8 "under-training" band, and >1.5 labelled `.high`),
/// so `testStatusVectorsMatchWatchBands` maps fixture statuses onto the bands
/// the watch distinguishes — the 0.8/1.3/1.5 inclusive-upper boundaries all
/// agree with the universal model, and the collapse below 0.8 is documented
/// in the fixture's `_comment`. The EWMA ratio itself is asserted verbatim.
final class ReadinessAcwrParityTests: XCTestCase {
    private struct Spans: Decodable {
        let acuteDays: Int
        let chronicDays: Int
        let lookbackDays: Int
        let readinessRecoverBelow: Int
        let readinessPushAbove: Int
    }
    private struct AcwrStatusVector: Decodable {
        let id: String
        let ratio: Double?
        let status: String
    }
    private struct AcwrRatioVector: Decodable {
        let id: String
        let dailyLoads: [Double]
        let expected: Double?
    }
    private struct ReadinessVector: Decodable {
        let id: String
        let acwr: Double?
        let expectedScore: Int?
        let expectedZone: String?
    }
    private struct Fixture: Decodable {
        let spans: Spans
        let acwrStatus: [AcwrStatusVector]
        let acwrRatio: [AcwrRatioVector]
        let readiness: [ReadinessVector]
    }

    private static let fixture: Fixture = {
        #if SWIFT_PACKAGE
        let resourceURL = Bundle.module.url(forResource: "readiness-acwr-parity", withExtension: "json")
        #else
        let resourceURL: URL? = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/readiness-acwr-parity.json")
        #endif
        guard let resourceURL else {
            fatalError("Missing readiness-acwr-parity.json test resource")
        }
        do {
            return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: resourceURL))
        } catch {
            fatalError("Invalid readiness/ACWR parity fixture: \(error)")
        }
    }()

    private static let ratioTolerance = 1e-9

    // Watch ACWRRiskBand uses a compact 4-band model: nil for no-data, `.low`
    // collapses the universal sub-0.8 range (including under-training), and
    // >1.5 is `.high` (the universal model calls it danger).
    private func expectedWatchBand(status: String) -> ACWRRiskBand? {
        switch status {
        case "noData": return nil
        case "underTraining", "low": return .low
        case "optimal": return .optimal
        case "caution": return .caution
        case "danger": return .high
        default: XCTFail("Unknown fixture status \(status)"); return nil
        }
    }

    func testAcwrRatioMatchesSharedVectors() {
        for vector in Self.fixture.acwrRatio {
            let ratio = ewmaAcwr(dailyLoads: vector.dailyLoads)
            if let expected = vector.expected {
                guard let ratio else {
                    XCTFail("\(vector.id): expected \(expected), got nil")
                    continue
                }
                XCTAssertEqual(ratio, expected, accuracy: Self.ratioTolerance, vector.id)
            } else {
                XCTAssertNil(ratio, "\(vector.id): expected nil, got \(String(describing: ratio))")
            }
        }
    }

    func testStatusVectorsMatchWatchBands() {
        for vector in Self.fixture.acwrStatus {
            let band = StatusPresentation.acwrRiskBand(vector.ratio)
            XCTAssertEqual(band, expectedWatchBand(status: vector.status), vector.id)
        }
    }

    func testReadinessVectorsMapToWatchLabels() {
        for vector in Self.fixture.readiness {
            let label = StatusPresentation.readinessZoneLabel(vector.expectedZone)
            // Recover/Maintain/Push are the only zones the watch distinguishes.
            let expected = vector.expectedZone.map { $0.capitalized }
            XCTAssertEqual(label, expected, vector.id)
        }
    }
}
