#!/usr/bin/env bash
# Local dev environment (issue #95): start the local Supabase stack (Docker),
# point the vite dev server at it, and run it.
#
# Writes .env.development.local (gitignored), which vite loads ONLY in dev
# mode — `npm run build` / fastlane / Vercel never read it, so production
# bundles always keep the hosted Supabase project.
#
# Seeded login: dev@sendmeter.test / devpassword  (supabase/seed.sql)
# Reset data anytime with: npm run db:reset
set -euo pipefail
cd "$(dirname "$0")/.."

npx supabase start

eval "$(npx supabase status -o env 2>/dev/null | grep -E '^(API_URL|PUBLISHABLE_KEY)=')"
cat > .env.development.local <<EOF
# Generated by scripts/dev-local.sh — points the DEV server at local Supabase.
# Delete this file to point npm run dev back at the hosted project.
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$PUBLISHABLE_KEY
VITE_DEV_AUTO_LOGIN=true
EOF
echo "→ dev server will use local Supabase at $API_URL and auto-login the seeded user"
echo "→ add ?auth to disable auto-login (cached sessions remain signed in)"
echo "→ delete .env.development.local to point npm run dev back at hosted Supabase"

exec npm run dev
